### ISSUE TITLE
volledige oplossing

### ISSUE THREAD

**Issue by josjelodder** [ideas-edu/logictools#413]
het vragen naar een volledige oplossing in logex-equivalenties lukt niet (bij de normaalvormen gaat het wel goed)

Uncaught TypeError: Cannot read properties of undefined (reading 'getText')
    at sn.showSolution (TwoWayController.js:212:73)
    at sn.<anonymous> (ExerciseController.js:33:12)

**Comment by BenEdV** [comment]
Op https://www.bendevries.com/logictools/main/ werkt het wel, zie dat er ook een "voltooi mijn oplossing" optie is. Het lijkt erop dat er nog een oude versie van logex op http://ideas.cs.uu.nl/logex/ draait. @alexgerdes  Zou jij hiernaar kunnen kijken?
